# This is a basic workflow to help you get started with Actions

name: Test Pull request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
      - cron: "0 8 * * 1" # At 08:00 AM, only on Monday

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      # Checkout just this repo 
      - name: Checkout runtime repo
        uses: actions/checkout@v3
      
      # Setup Python to run the Scala Tests 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Setup Java to run the Scala Tests
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: befor install -> install python3-pip
        run:  sudo apt-get install -y python3-pip

      - name: befor install -> upgrade pip setuptools six
        run:  |
          pip install --user --upgrade pip setuptools six 
          pip3 install --user --upgrade pip setuptools six 

      - name: Python verison
        run: |
          python --version
          python3 --version
          python3.10 --version
          pip --version
          pip3 --version
          pip3.10 --version

      - name: befor install -> setup.sh
        run:  |
          docker image ls && docker image rm $(docker image ls -q) -f && ./tools/travis/setup.sh

      - name: script -> build
        run:  |
          ./tools/travis/build.sh
      
      - name: script -> deploy
        run:  |
          pip install --user jinja2==3.0.3
          ./tools/travis/deploy.sh 
      - name: script-> test
        run:  |
          ./tools/travis/test.sh 